theme: minima  #jekyll-theme-cayman

title: Qibin Hou, Associate Professor at School of Computer Science, Nankai University

# User settings
author: https://github.com/Andrew-Qibin
username: Qibin Hou
email: andrewhoux@gmail.com
# username: Qibin Hou
# user_description: I'm a research fellow at NUS
# user_title: Research Fellow

description: > # this means to ignore newlines until "show_excerpts:"
  I am currently an associate frofessor at School of Computer Science.


show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    #twitter: xxxx
    github:  Andrew-Qibin

plugins:
# - jekyll-sitemap
# - jekyll-mentions
# - jekyll-paginate
- jekyll-seo-tag
# - jekyll-redirect-from
# - jekyll-default-layout
- jekyll-feed
# - jekyll-commonmark
# - jekyll-include-cache
# - jemoji
